'use strict';(function(){(function(){var cmpScriptElement=document.createElement('script');var firstScript=document.getElementsByTagName('script')[0];cmpScriptElement.async=true;cmpScriptElement.type='text/javascript';var cmpVersion='https://quantcast.mgr.consensu.org/cmp.js';cmpScriptElement.src=cmpVersion;firstScript.parentNode.insertBefore(cmpScriptElement,firstScript);})();(function(){var css=""
+" .qc-cmp-button { "
+"   background-color: #0080ff !important; "
+"   border-color: #0080ff !important; "
+" } "
+" .qc-cmp-button:hover { "
+"   border-color: #0080ff !important; "
+" } "
+" .qc-cmp-alt-action, "
+" .qc-cmp-link { "
+"   color: #0080ff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   background-color: #0080ff !important; "
+"   border-color: #0080ff !important; "
+" } "
+" .qc-cmp-button { "
+"   color: #fff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button:hover { "
+"   color: #fff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   color: #fff !important; "
+" } "
+" .qc-cmp-button.qc-cmp-secondary-button { "
+"   background-color: #888 !important; "
+"   border-color: transparent !important; "
+" } "
+" .qc-cmp-ui, "
+" .qc-cmp-ui .qc-cmp-title, "
+" .qc-cmp-ui .qc-cmp-table, "
+" .qc-cmp-ui .qc-cmp-messaging, "
+" .qc-cmp-ui .qc-cmp-sub-title, "
+" .qc-cmp-ui .qc-cmp-vendor-list, "
+" .qc-cmp-ui .qc-cmp-purpose-info, "
+" .qc-cmp-ui .qc-cmp-table-header, "
+" .qc-cmp-ui .qc-cmp-beta-messaging, "
+" .qc-cmp-ui .qc-cmp-main-messaging, "
+" .qc-cmp-ui .qc-cmp-vendor-list-title{ "
+"   color: #333 !important; "
+" } "
+" .qc-cmp-ui a, "
+" .qc-cmp-ui .qc-cmp-alt-action { "
+"   color: #0080ff !important; "
+" } "
+" .qc-cmp-ui { "
+"   background-color: #F2F7FA !important; "
+" } "
+" .qc-cmp-small-toggle.qc-cmp-toggle-on, "
+" .qc-cmp-toggle.qc-cmp-toggle-on { "
+"   background-color: #0080ff!important; "
+"   border-color: #0080ff!important; "
+" } "
+".qc-cmp-ui thead th {background: transparent !important;}.qc-cmp-ui td,.qc-cmp-ui th {border: none !important;padding: 0 !important;}td.qc-cmp-table-row {border-top: 1px solid #000000 !important;}td.qc-cmp-enabled-cell,td.qc-cmp-table-header,td.qc-cmp-company-cell {padding: 0 20px !important;}td.qc-cmp-vendor-info-content {padding: 0 20px 15px !important;}td.qc-cmp-table-row {padding: 10px 20px !important;}.qc-cmp-vendor-description-el {font-size: 14px !important;}.qc-cmp-toggle {-webkit-box-sizing: content-box !important;-moz-box-sizing: content-box !important;box-sizing: content-box !important;}.qc-cmp-ui-container a,.qc-cmp-ui-container button {font-family: Arial,Verdana,sans-serif !important;}.qc-cmp-purpose-description {font-size: 14px !important;margin: 10px 0 !important;width: calc(100% - 200px) !important;line-height: normal !important;}.qc-cmp-toggle-status {font-family: Arial,Verdana,sans-serif !important;font-size: 12px !important;font-weight: 700 !important;opacity: .8 !important;margin: 0 !important;padding: 6px 0 0 !important;text-align: center !important;}.qc-cmp-ui-content,.qc-cmp-ui-container.qc-cmp-showing,.qc-cmp-ui.qc-cmp-showing {overflow-y: auto !important;}.qc-cmp-persistent-link,.qc-cmp-link-text,.qc-cmp-qc-link {display: none !important;}.qc-cmp-ui-content .qc-cmp-qc-link-container{ display:none!important; height:0px!important; width:0px!important; padding:0px!important; margin:0px!important }.qc-cmp-ui, .qc-cmp-ui .qc-cmp-title, .qc-cmp-ui .qc-cmp-table, .qc-cmp-ui .qc-cmp-messaging, .qc-cmp-ui .qc-cmp-sub-title, .qc-cmp-ui .qc-cmp-vendor-list, .qc-cmp-ui .qc-cmp-purpose-info, .qc-cmp-ui .qc-cmp-table-header, .qc-cmp-ui .qc-cmp-beta-messaging, .qc-cmp-ui .qc-cmp-main-messaging, .qc-cmp-ui .qc-cmp-vendor-list-title {font-family: &amp;quote;Roboto&amp;quote;,Arial,sans-serif;}.qc-cmp-button {transition: transform .05s linear,opacity .05s linear,-webkit-transform .05s linear}.qc-cmp-button {background-color: #0080ff !important;border-color: #0080ff !important;color: #fff;}.qc-cmp-button:hover {background-color: #034aa6 !important;border-color: #034aa6 !important;}.qc-cmp-button.qc-cmp-secondary-button {background-color: #888 !important;border-color: #888 !important;color: #fff;}.qc-cmp-button.qc-cmp-secondary-button:hover {background-color: #555 !important;border-color: #555 !important;}.qc-cmp-toggle-off {background-color: #888 !important;border-color: #888 !important;}.qc-cmp-back {margin: 0 0 0 -5px !important;}.qc-cmp-back:before {display: none !important;}.qc-cmp-arrow-down {background: url(&amp;quote;data:image/svg+xml;base64,JTNDc3ZnIHhtbG5zPSdodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2Zycgdmlld0JveD0nMCAwIDE2IDE2JyBmaWxsPSdub25lJyBzdHJva2U9JyUyM0ZGRicgc3Ryb2tlLXdpZHRoPScyJyBzdHJva2UtbGluZWNhcD0ncm91bmQnIHN0cm9rZS1saW5lam9pbj0ncm91bmQnJTNFJTNDcGF0aCBkPSdNMiA1bDYgNiA2LTYnLyUzRSUzQy9zdmclM0U&#x3D;&amp;quote;) 50% no-repeat !important;}"
+" .qc-cmp-table { border: 1px solid #000000 !important;} .qc-cmp-table-row { border-top: 1px solid #000000 !important; } .qc-cmp-table-row:last-child {  border-bottom: 1px solid #000000 !important; } .qc-cmp-toggle-status { color: #000000 !important; }  .qc-cmp-arrow-down { background: url(\"data:image\/svg+xml,%3Csvg xmlns=\'http:\/\/www.w3.org\/2000\/svg\' viewBox=\'0 0 16 16\' fill=\'none\' stroke=\'%234D545D\' stroke-width=\'2\' stroke-linecap=\'round\' stroke-linejoin=\'round\'%3E %3Cpolyline points=\'2 5 8 11 14 5\'\/%3E %3C\/svg%3E\") center no-repeat; }"
+"";var stylesElement=document.createElement('style');var re=new RegExp('&amp;quote;','g');css=css.replace(re,'"');stylesElement.type='text/css';if(stylesElement.styleSheet){stylesElement.styleSheet.cssText=css;}else{stylesElement.appendChild(document.createTextNode(css));}
var head=document.head||document.getElementsByTagName('head')[0];head.appendChild(stylesElement);})();(function(){var gdprAppliesGlobally=true;function addFrame(){if(!window.frames['__cmpLocator']){if(document.body){(function(){var body=document.body;var iframe=document.createElement('iframe');iframe.name='__cmpLocator';iframe.style.cssText='display:none';body.appendChild(iframe);})();}else{setTimeout(addFrame,5);}}}
addFrame();function cmpMsgHandler(event){var json=void 0;var msgIsString=typeof event.data==='string';if(msgIsString){json=event.data.indexOf('__cmpCall')!==-1?JSON.parse(event.data):{};}else{json=event.data;}
if(json.__cmpCall){(function(){var cmpCall=json.__cmpCall;window.__cmp(cmpCall.command,cmpCall.parameter,function(returnValue,success){var returnMsg={'__cmpReturn':{'success':success,'callId':cmpCall.callId,'returnValue':returnValue}};event.source.postMessage(msgIsString?JSON.stringify(returnMsg):returnMsg,'*');});})();}}
window.__cmp=function(command){var arg=arguments;var returnValue=null;if(!arg.length){returnValue=__cmp.a;}else if(arg[0]==='ping'){arg[2]({'cmpLoaded':false,'gdprAppliesGlobally':gdprAppliesGlobally},true);}else if(command==='__cmp'){returnValue=false;}else{if(typeof __cmp.a==='undefined'){__cmp.a=[];}
__cmp.a.push([].slice.apply(arg));}
return returnValue}
window.__cmp.gdprAppliesGlobally=gdprAppliesGlobally;window.__cmp.msgHandler=cmpMsgHandler;if(window.addEventListener){window.addEventListener('message',cmpMsgHandler,false);}else{window.attachEvent('onmessage',cmpMsgHandler);}})();var autoDetectedLanguage='en';function splitLang(lang){return lang.length>2?lang.split('-')[0]:lang;};function isSupported(lang){var langs=['bg','cs','da','de','el','en','es','et','fi','fr','ga','hr','hu','it','lt','lv','mt','nl','pl','pt','ro','sk','sl','sv'];return langs.indexOf(lang)===-1?false:true;};if(isSupported(splitLang(document.documentElement.lang))){autoDetectedLanguage=splitLang(document.documentElement.lang);}else if(isSupported(splitLang(navigator.language))){autoDetectedLanguage=splitLang(navigator.language);};var choiceMilliSeconds=(new Date).getTime();window.__cmp('init',{'Non IAB Vendor List URL':'https://quantcast.mgr.consensu.org'.concat('/choice').concat('/AaqDBHcavs6a0').concat('/www.researchgate.net').concat('/.well-known/noniab-vendorlist.json').concat('?timestamp','=',choiceMilliSeconds),'Display Persistent Consent Link':false,'No Option':false,'Default Value for Toggles':'off','Google Personalization':true,'Consent Scope':'service group','Language':'en','Initial Screen Accept Button Text':'I accept','PCode':'AaqDBHcavs6a0','Display UI':'inEU','Purpose Screen Vendor Link Text':'All vendors ','Initial Screen Purpose Link Text':'Show purposes','UI Layout':'banner','Publisher Name':'ResearchGate','Mode':1,'Purpose Screen Body Text':'You can set your consent preferences and determine how you want your data to be used based on the purposes below. Each purpose has a description so that you know how we and partners use your data. You may set your preferences for \u201CThird Party Vendors.\u201D Below you will also find \u201COther,\u201D where you may set your preferences regarding our use of Google\'s technologies. Under \u201CAll Vendors\u201D you may set your preferences per specific Vendor for \"IAB- Vendors\" and \u201CNon- IAB- Vendors,\u201D meaning Vendors not currently participating in the IAB\u2019s Transparency and Consent Framework. ','Publisher Purpose Legitimate Interest IDs':[1,2,3,4,5],'Soft Opt-in Enabled':false,'Min Days Between UI Displays':30,'Publisher Purpose IDs':[1,2,3,4,5],'Consent Scope Group URL':'https://www.researchgate.net/quantcast/cookies','Cookie Domain':'researchgate.net','Publisher Vendor List URL':'https://quantcast.mgr.consensu.org'.concat('/choice').concat('/AaqDBHcavs6a0').concat('/www.researchgate.net').concat('/.well-known/pubvendors.json').concat('?timestamp','=',choiceMilliSeconds),'Initial Screen Body Text Option':1,'Initial Screen Reject Button Text':'I do not accept'});})();